<?php
/**
  * @file
  * microbe check report module file
  */

/**
 * Implements hook_menu().
 */
function checkreport_menu() {
  $items['checkreport/%/%'] = array(
    'title' => '检测报告',
    'title callback' => 'menufun_checkreport_title',
    'title arguments' => array(1,2),
    'description' => t('check report page'),
    'page callback' => 'menufun_checkreport_content',
    'file' => 'menufun_checkreport.inc',
    'page arguments' => array(1),
    'access callback' => 'user_access',
    'access arguments' => array('see report'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_permission()
 */
function checkreport_permission() {
  return array(
   'see report' => array(
    'title' => t('查看报告'),
    'description' => t('允许注册用户查看报告'),
   ),
  );
}

/**
 * checkreport_title function
 */
function menufun_checkreport_title($sample_id = NULL, $title_data = NULL){
  return t('@title_data @sample_id 检测报告', array('@sample_id' => $sample_id, '@title_data' => $title_data));
}
