<?php
/**
 * @file
 * Support for bond sample
 */

/**
 * Implements hook_user_view().
 */
function bondsample_user_view($account) {
  $fields = array();
  $sampleid_data = "";
  $relationship = array(
    'A' => '本人',
    'B' => '爱人',
    'C' => '女儿',
    'D' => '儿子',
    'E' => '父亲',
    'F' => '母亲',
    'G' => '其它',
  );


  $form_sids = db_query("SELECT sid FROM {webform_submissions} WHERE uid=:uid AND nid=:nid", array(':uid' => $account->uid, ':nid' => 13));
  $account->content['samples'] = array(
    '#type' => 'user_profile_category',
    '#title' => t('我绑定的样品'),
  );
  foreach($form_sids as $row) {
    $result = db_query("SELECT * FROM {webform_submitted_data} WHERE sid=:sid", array(':sid' => $row->sid));
    foreach ($result as $field) {
      switch ( $field -> cid ){
        case 1:
          $rela_data = $field -> data;
          break;
        case 2:
          $otherrela_data = $field -> data;
          break;
        case 3:
          $sampleid_data = "RealOral".$field -> data;
          break;
        case 4:
          if( $otherrela_data ){
            $title_data = "我". $otherrela_data ."（".$field -> data."）的口腔样品:";
          }else{
            $title_data = "我". $relationship[$rela_data] ."（".$field -> data."）的口腔样品:";
          }
          break;
      }
    }
    $account->content['samples'][$sampleid_data] = array(
      '#type' => 'user_profile_item',
      '#title' => $title_data,
      '#markup' => "样品编号：$sampleid_data<br>检测报告:",
    );
  }
  if(!$sampleid_data) {
    $account->content['samples']['no'] = array(
      '#type' => 'user_profile_item',
      '#title' => t('尚未成功绑定'),
      '#markup' => "",
    );
  }
}
